# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='home/media/'),
        ),
    ]
