# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180124_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/media/'),
        ),
    ]
