# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_images_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='user_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
