# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_images_user_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_image', models.ImageField(blank=True, null=True, upload_to='homepage/media/')),
                ('title', models.CharField(blank=True, default='club', max_length=200, null=True)),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
