# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_staffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminify',
            field=models.BooleanField(default=False),
        ),
    ]
